apiVersion: v1
kind: Pod
metadata:
  name: sender
spec:
  containers:
    - name: sender
      image: docker.io/tylergu1998/tidb-writer:v1
      imagePullPolicy: Always
      env:
        - name: TIDB_HOST
          value: "test-cluster-tidb.acto-namespace.svc.cluster.local"
        - name: TIDB_PORT
          value: "4000"
        - name: TIDB_USER
          value: "root"
        - name: TIDB_PASSWORD
          value: "root"
        - name: TIDB_DATABASE
          value: "test"