apiVersion: v1
kind: Pod
metadata:
  name: mariadb-writer
spec:
  containers:
    - name: mariadb-writer
      image: docker.io/tylergu1998/mariadb-writer:v1
      imagePullPolicy: Always
      env:
        - name: MARIADB_HOST
          value: "test-cluster.acto-namespace.svc.cluster.local"
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_USER
          value: "root"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: root-password
        - name: MARIADB_DATABASE
          value: "test"