apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: partition
spec:
  action: partition
  mode: all
  selector:
    nodes:
      - k3d-test-agent-2
  direction: both
  target:
    mode: all
    selector:
      namespaces:
        - default