apiVersion: v1
kind: Pod
metadata:
  name: sender
spec:
  containers:
    - name: sender
      image: docker.io/tylergu1998/rabbitmq-sender:v1
      imagePullPolicy: Always
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: hello-world-default-user
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hello-world-default-user
              key: password
        - name: SECRET_HOST
          valueFrom:
            secretKeyRef:
              name: hello-world-default-user
              key: host
